name: CI/CD for EC-CUBE

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - '**'
      - '!*.md'
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!*.md'
jobs:
  verify-merged-to-staging:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/verify-merged-to-staging.yml

  dockerbuild:
    needs: verify-merged-to-staging
    with:
      event_name: ${{ github.event_name }}
    uses: ./.github/workflows/dockerbuild.yml
  php-cs-fixer:
    with:
      ref_name: ${{ github.ref_name }}
      base_ref: ${{ github.base_ref }}
      event_name: ${{ github.event_name }}
      owner: ${{ github.repository_owner }}
    needs: [ dockerbuild ]
    uses: ./.github/workflows/php-cs-fixer.yml
  phpstan:
    with:
      ref_name: ${{ github.ref_name }}
      base_ref: ${{ github.base_ref }}
      event_name: ${{ github.event_name }}
      owner: ${{ github.repository_owner }}
    needs: [ php-cs-fixer ]
    uses: ./.github/workflows/phpstan.yml
  unit-tests:
    with:
      ref_name: ${{ github.ref_name }}
      base_ref: ${{ github.base_ref }}
      event_name: ${{ github.event_name }}
      owner: ${{ github.repository_owner }}
    needs: [ php-cs-fixer ]
    uses: ./.github/workflows/unit-tests.yml
  e2e-tests:
    with:
      ref_name: ${{ github.ref_name }}
      base_ref: ${{ github.base_ref }}
      event_name: ${{ github.event_name }}
      owner: ${{ github.repository_owner }}
    needs: [ php-cs-fixer ]
    uses: ./.github/workflows/e2e-tests.yml
  success:
    needs:
      - phpstan
      - unit-tests
      - e2e-tests
    uses: ./.github/workflows/success.yml
